{application, ibrowse,
        [{description, "HTTP client application"},
         {vsn, "1.4.1-json"},
         {modules, [ ibrowse, 
		     ibrowse_http_client, 
		     ibrowse_app, 
		     ibrowse_sup, 
		     ibrowse_lb, 
		     ibrowse_lib,
		 	 rfc4627 ]},
         {registered, []},
         {applications, [kernel,stdlib,sasl]},
	 {env, []},
	 {mod, {ibrowse_app, []}}]}.
